In [139]:
!pip install ratelim tenacity
#install packages

Requirement already satisfied: ratelim in /opt/anaconda3/lib/python3.13/site-packages (0.1.6)
Requirement already satisfied: tenacity in /opt/anaconda3/lib/python3.13/site-packages (9.1.2)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.13/site-packages (from ratelim) (5.2.1)

In [2]:
!pip install requests
#install packages

Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2026.1.4)

In [3]:
import ratelim
import tenacity
import requests
#import packages

In [4]:
import sys
# Prints the path to the active Python executable
print(sys.executable) 
# Prints the root directory of the current environment
print(sys.prefix)

/opt/anaconda3/bin/python
/opt/anaconda3

In [140]:
!pip install virtualenv
!virtualenv myenv
!myenv\Scripts\activate
!myenv\Scripts\pip.exe install google-api-python-client
#Pulled from Google API github documentation, needed to interact with their APIs

Requirement already satisfied: virtualenv in /opt/anaconda3/lib/python3.13/site-packages (21.2.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /opt/anaconda3/lib/python3.13/site-packages (from virtualenv) (0.4.0)
Requirement already satisfied: filelock<4,>=3.24.2 in /opt/anaconda3/lib/python3.13/site-packages (from virtualenv) (3.25.2)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /opt/anaconda3/lib/python3.13/site-packages (from virtualenv) (4.5.0)
Requirement already satisfied: python-discovery>=1 in /opt/anaconda3/lib/python3.13/site-packages (from virtualenv) (1.2.2)
created virtual environment CPython3.13.9.final.0-64-arm64 in 561ms
  creator CPython3Posix(dest=/Users/baileycarpenter/anaconda_projects/dffff21d-ef4f-4304-88bc-75e68200ebb4/myenv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/baileycarpenter/Library/Caches/virtualenv)
    added seed packages: pip==26.0.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
zsh:1: command not found: myenvScriptsactivate
zsh:1: command not found: myenvScriptspip.exe

In [32]:
url = 'https://www.googleapis.com/youtube/v3/search?key=AIzaSyAeOMGKFtTTVjxz5opGfJxoFdDQFMk_bsY'
#names my API with included key as 'url'

In [33]:
response = requests.get(url) #first request

In [34]:
response #checking status

In [22]:
url #ensuring it is coded properly

'https://www.googleapis.com/youtube/v3/search?api_key=AIzaSyAeOMGKFtTTVjxz5opGfJxoFdDQFMk_bsY'

In [35]:
print(f"Request returned {response.status_code} : '{response.reason}'") #confirming status of request

Request returned 200 : 'OK'

In [25]:
!pip install --upgrade google-api-python-client #installing Google API client

Collecting google-api-python-client
  Downloading google_api_python_client-2.193.0-py3-none-any.whl.metadata (7.0 kB)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 (from google-api-python-client)
  Downloading google_auth-2.49.1-py3-none-any.whl.metadata (6.2 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)
  Downloading google_auth_httplib2-0.3.1-py3-none-any.whl.metadata (3.0 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.30.2-py3-none-any.whl.metadata (3.1 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.74.0-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.3)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.27.2-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/anaconda3/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (46.0.3)
Requirement already satisfied: pyparsing<4,>=3.1 in /opt/anaconda3/lib/python3.13/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.1.4)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (2.23)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/anaconda3/lib/python3.13/site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.1)
Downloading google_api_python_client-2.193.0-py3-none-any.whl (14.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 2.6 MB/s  0:00:062.5 MB/s eta 0:00:01:01
Downloading google_api_core-2.30.2-py3-none-any.whl (173 kB)
Downloading google_auth-2.49.1-py3-none-any.whl (240 kB)
Downloading google_auth_httplib2-0.3.1-py3-none-any.whl (9.5 kB)
Downloading googleapis_common_protos-1.74.0-py3-none-any.whl (300 kB)
Downloading httplib2-0.31.2-py3-none-any.whl (91 kB)
Downloading proto_plus-1.27.2-py3-none-any.whl (50 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Installing collected packages: uritemplate, proto-plus, httplib2, googleapis-common-protos, google-auth, google-auth-httplib2, google-api-core, google-api-python-client
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [google-api-python-client][0m [google-api-python-client]
Successfully installed google-api-core-2.30.2 google-api-python-client-2.193.0 google-auth-2.49.1 google-auth-httplib2-0.3.1 googleapis-common-protos-1.74.0 httplib2-0.31.2 proto-plus-1.27.2 uritemplate-4.2.0

In [141]:
import os
import pandas as pd
import googleapiclient.discovery
#importing the packages needed
def main(): 
    api_service_name = "youtube" #name of API service
    api_version = "v3" #version of API
    DEVELOPER_KEY = "AIzaSyAeOMGKFtTTVjxz5opGfJxoFdDQFMk_bsY" #API key

    youtube = googleapiclient.discovery.build(
        api_service_name, api_version, developerKey = DEVELOPER_KEY)
    #defines youtube

    request = youtube.search().list( #defines request as a youtube search list
        part="snippet", #parameter that defines the extent of the request
        channelType="any", #parameter defines channeltype as 'any'
        eventType="completed", #parameter sets returned videos as ones that have been 'completed'
        maxResults=50, #max results returned
        order="date", #orders returns in chronological order
        q="skinny", #'q' refers to the search term,  defined as "skinny"
        relevanceLanguage="en", #only videos in english returned
        safeSearch="none", #safesearch is not on, due to the sensitive topic matter
        topicId="/m/041xxh", #defines the topic of video returned, "/m/041xxh" returning the topic 'physical attractiveness (beauty)
        type="video" #defines type of video returned
    )
    response = request.execute() #executes request
    
    video_data = [] #creates an empty list for the data to be stored
    
    # Extract relevant information from each video item
    for item in response['items']: #for loop that extracts relevant information from each video item
        video_info = {
            'video_id': item['id']['videoId'], 
            'title': item['snippet']['title'],
            'channel_title': item['snippet']['channelTitle'],
            'published_at': item['snippet']['publishedAt'],
            'description': item['snippet']['description']
        }
        video_data.append(video_info)
    df = pd.DataFrame(video_data) #creates pandas dataframe from video_data
    
    return df

      video_id                                              title  \
0  UAB7gvfF4a8                               Skinny Vs. Plus Size
1  kpuwhBAjoFE  Exploring Body Image: The Enduring Allure of B...
2  OxtaRHjYP9o  Do people prefer a plus size person or a(skinn...
3  K3tdPTc9NMw  What EVERY skinny guy should know | The Book o...

             channel_title          published_at  \
0                SuperLife  2026-02-26T09:00:03Z
1  The Bougie Hippie Chick  2024-12-07T13:22:56Z
2       CLIPS PODCAST SHOW  2024-10-24T14:22:05Z
3             Come On, Man  2024-05-02T03:11:12Z

                                         description
0  JOIN!- https://www.patreon.com/10058586/join :...
1  Exploring Body Image: The Enduring Allure of B...
2
3  Explore the journey from skinny to muscular, f...

In [55]:
df #viewing returned data

,video_id,title,channel_title,published_at,description
0,UAB7gvfF4a8,Skinny Vs. Plus Size,SuperLife,2026-02-26T09:00:03Z,JOIN!- https://www.patreon.com/10058586/join :...
1,kpuwhBAjoFE,Exploring Body Image: The Enduring Allure of B...,The Bougie Hippie Chick,2024-12-07T13:22:56Z,Exploring Body Image: The Enduring Allure of B...
2,OxtaRHjYP9o,Do people prefer a plus size person or a(skinn...,CLIPS PODCAST SHOW,2024-10-24T14:22:05Z,
3,K3tdPTc9NMw,What EVERY skinny guy should know | The Book o...,"Come On, Man",2024-05-02T03:11:12Z,"Explore the journey from skinny to muscular, f..."

In [127]:
def main(): 
    api_service_name = "youtube"
    api_version = "v3"
    DEVELOPER_KEY = "AIzaSyAeOMGKFtTTVjxz5opGfJxoFdDQFMk_bsY"

    youtube = googleapiclient.discovery.build(
        api_service_name, api_version, developerKey = DEVELOPER_KEY)

    request = youtube.search().list(
        part="snippet",
        channelType="any",
        eventType="completed",
        maxResults=50,
        order="date",
        q="omad diet", #changed search term to omad diet, referring to 'one meal a day' diets
        relevanceLanguage="en",
        safeSearch="none",
        type="video"
    ) #also removed the topic parameter to broaden returned results
    response = request.execute()
    
    video_data2 = [] #creates list under new name
    
    for item in response['items']:
        video_info2 = {
            'video_id': item['id']['videoId'],
            'title': item['snippet']['title'],
            'channel_title': item['snippet']['channelTitle'],
            'published_at': item['snippet']['publishedAt'],
            'description': item['snippet']['description']
        }
        video_data2.append(video_info2)
    
    # Create a pandas DataFrame
    df2 = pd.DataFrame(video_data2)
    
    return df2

      video_id                                              title  \
0  UAB7gvfF4a8                               Skinny Vs. Plus Size
1  kpuwhBAjoFE  Exploring Body Image: The Enduring Allure of B...
2  OxtaRHjYP9o  Do people prefer a plus size person or a(skinn...
3  K3tdPTc9NMw  What EVERY skinny guy should know | The Book o...

             channel_title          published_at  \
0                SuperLife  2026-02-26T09:00:03Z
1  The Bougie Hippie Chick  2024-12-07T13:22:56Z
2       CLIPS PODCAST SHOW  2024-10-24T14:22:05Z
3             Come On, Man  2024-05-02T03:11:12Z

                                         description
0  JOIN!- https://www.patreon.com/10058586/join :...
1  Exploring Body Image: The Enduring Allure of B...
2
3  Explore the journey from skinny to muscular, f...

In [128]:
df2 #display uncleaned dataframe

,video_id,title,channel_title,published_at,description
0,FO7RPT6XLuQ,"OMAD, 2MAD, or just going mad? Fasting on a Ke...",Carnivore Talk,2026-04-14T02:46:32Z,"OMAD, 2MAD, or Just Plain MAD? Intermittent Fa..."
1,nw8SYbEARig,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-04-04T07:24:25Z,Kayla lost 80 pounds with intermittent fasting...
2,5yzDKwnTpnE,Intermittent Fasting and CKD: Is One Meal A Da...,Dadvice TV - Kidney Health Coach,2026-04-01T12:28:56Z,Are you confused about what to eat for Stage 3...
3,WmhVxALFxdY,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03-28T07:43:39Z,Kayla lost 80 pounds with intermittent fasting...
4,fsKfncwtJBE,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03-21T07:17:19Z,Kayla lost 80 pounds with intermittent fasting...
5,M0knw4F1wKc,"OMAD Keto Dinner Prep: Chicken, mince eggs A...",Miss Sarah M,2026-03-18T08:11:59Z,
6,A62b1L8gh-A,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03-07T08:17:49Z,Kayla lost 80 pounds with intermittent fasting...
7,ElteeBIkZvY,"Biblical Perspective Mindful Eating, Fasting, ...",BGK Mindful Eating,2026-02-25T06:52:57Z,"This isn't about eating less, eliminating, or ..."
8,Ndmm6U_93Bo,"New Year, New You! Intermittent Fasting, OMAD ...",Six Miles To Supper,2026-01-03T08:04:36Z,Kayla lost 80 pounds with intermittent fasting...
9,Ytxo_6-SWdo,OMAD Shaggy Locs Explains The Benefits &amp; I...,BSA Queen Goddess,2025-12-04T17:12:52Z,One Meal A Day Shaggy Locs Explains Why U Shou...
10,FWI38bG5JIw,Live Eating Of Todays OMAD Fastbreaking Meal,MIKE SAHA,2025-11-26T11:28:54Z,Live Eating Of Todays OMAD Fastbreaking Meal #...
11,qP-ZbAb-crU,"Live Cooking And Eating OMAD Meal, Speaking",MIKE SAHA,2025-10-24T06:07:35Z,"Live Cooking And Eating OMAD Meal, Speaking #F..."
12,EFbZpYAPtQg,OMAD diet plan chart (weight loss ),awais latif,2025-10-15T10:57:01Z,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
13,SE_Ssjyc9JE,Eating My OMAD Fastbreaking Meal (One Meal A D...,MIKE SAHA,2025-10-14T09:36:34Z,Eating My OMAD Fastbreaking Meal (One Meal A D...
14,5cfUhAqcM_c,OMAD diet chart for weight loss,awais latif,2025-10-11T09:41:50Z,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
15,Wqm67-silS0,OMAD diet plan,awais latif,2025-10-10T07:59:18Z,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
16,ZVc47uu3KD0,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10-09T04:36:54Z,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
17,YQheeH5yeM4,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10-09T03:09:56Z,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
18,tz2YmLpH06I,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10-08T23:34:18Z,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
19,zUwGLKRByxc,Omad diet plan for weight loss,awais latif,2025-10-08T20:45:34Z,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
20,SrveDbiTQ_E,"JANGAN BUAT IF, OMAD #diet #fitness #fyp",Raeiz Hamed (RHTV),2025-10-07T11:24:44Z,trending #natural #viral Please Tekan Button S...
21,ziIJ4X3AnwQ,Day 1 Omad diet Weight loss diet starting weig...,Mieka The Habit Coach,2025-08-12T14:11:17Z,Join my skool community for fun monthly weight...
22,Irdvlv6O1PA,My OMAD Diet Rules | Case Study | Q&amp;A Live...,Fat to Fab,2025-07-11T15:01:16Z,For Personalized Diet Plans: Email - Enquiry@s...
23,RZjKtrT5UZs,MIKE SAHA LIVE OMAD MEALPREP / EATING,MIKE SAHA,2025-06-23T11:21:30Z,Mealprep video and eating ...
24,TP6epkBS6xY,LIVE MUKBANG OMAD MEAL EATING,MIKE SAHA,2025-06-09T11:45:50Z,LIVE MUKBANG OMAD MEAL EATING ...
25,0FNuOtrEmNk,Eating My Fastbreaking OMAD MEAL MIKE SAHA is ...,MIKE SAHA,2025-05-26T12:05:58Z,Eating my OMAD fastrbeaking meal ...
26,VkKZMb8uGVo,Mieka live Mukbang Omad diet #mukbang #eating ...,Mieka vs Nikki,2025-05-25T09:00:25Z,
27,Ii4b2ZerKhs,My Complete 30 Day OMAD Diet Weight Loss Chall...,Mieka The Habit Coach,2025-05-17T12:18:48Z,Join this channel to support their goals & Get...
28,S8dwV7TkwRc,| Day 6 | One meal a day diet #food #mukbang #...,MotionManTg,2025-03-21T12:19:53Z,
29,cjahrugNcwk,"Fasting &amp; Inflammation! Ready, Set, Go! OM...",My WeightLoss Journey By Keto Granny,2025-02-18T11:08:57Z,Join this channel to get access to perks: http...
30,mpkO8u4eU5Q,OMAD + A Cucumber For Weight Loss #weightloss ...,Mieka The Habit Coach,2024-11-23T13:00:09Z,Join this channel to support their goals & Get...
31,VKBgMvC_Ops,OMAD for 10 months✨️|OMAD diet results|OMAD be...,Jennifer Santos,2024-10-05T05:55:44Z,Don't underestimate the power of walking and f...
32,f2y7iTEyOik,The Ultimate Guide to the One Meal a Day Diet ...,Mike Cola,2024-08-03T11:09:23Z,The Ultimate Guide to the One Meal a Day Diet ...
33,NllKcY2nXRs,One Meal A Day (OMAD) Diet: How to Do it Corre...,Daniella Joy,2024-01-31T13:04:12Z,One Meal A Day (OMAD) Diet: How to Do it Corre...
34,igFVMTavE5Q,My Experience with OMAD + Carnivore Diet,Daniella Joy,2023-11-22T09:13:58Z,My Experience with OMAD + Carnivore Diet ... s...
35,Oc_hWisp4WM,Omad Diet Weight Loss Vlog Day 40 #weightloss ...,Mieka The Habit Coach,2023-10-13T12:45:23Z,I am on a weight loss journey to lose over 90 ...
36,uTei63rneH0,Live nutrition @DorianPicard : Omad / Carnivor...,ON THE WHEY,2023-10-11T22:33:04Z,Mon instagram : https://www.instagram.com/on_t...
37,u84wxd95ktY,Intermittent Fasting Schedule - Actual Hours a...,Intermittent Fasting Foodie,2023-09-18T01:20:00Z,I love intermittent fasting and have been eati...
38,0F_dcjNIz0o,Intermittent Fasting Schedule - Actual Hours a...,Intermittent Fasting Foodie,2023-09-10T23:13:00Z,I love intermittent fasting and have been eati...
39,SvH2tXzpKNg,Week of Fasting (&amp; Eating) My Exact Hours!...,Intermittent Fasting Foodie,2023-09-03T23:13:42Z,I love intermittent fasting and have been eati...
40,9lJXN9Yk3Bg,OMAD (ONE MEAL A DAY) SEPTEMBER WEIGHT LOSS CH...,Lih Lately,2023-09-01T09:31:07Z,loseweightfast #loseweighthealthy #omad #oneme...
41,V24FNaNOI0s,Do you know about OMAD Diet?,IHW tv,2023-08-31T12:06:35Z,OMAD Diet also known as warrior diet is all ab...
42,dQtEfqSudPE,Mastering OMAD: 10 Habits for Guaranteed Weigh...,Daniella Joy,2023-08-09T10:57:25Z,Mastering OMAD: 10 Habits for Guaranteed Weigh...
43,E2PCIUN39Aw,Episode #34 Omad weight loss.,AirborneOutdoorZ,2023-08-07T06:56:01Z,"Acceptance,commitment training."
44,04ouBqx0YGs,YOU CAN PRIORITIZE WEIGHT LOSS VIA OMAD MEALS ...,Daniella Joy,2023-07-21T06:58:06Z,YOU CAN PRIORITIZE WEIGHT LOSS VIA OMAD MEALS ...
45,P0koLtpXH7A,Live at 5:00 | OMAD One Meal A Day,Live Savage,2023-07-20T10:48:41Z,And other questions and answers!
46,ZIxqd_vCS1E,THE FASTER THE OMAD EATING WINDOW THE FASTER T...,Daniella Joy,2023-07-02T10:33:28Z,THE FASTER THE OMAD EATING WINDOW THE FASTER T...
47,bOHkMwWdnPs,Why Do People Gain Weight After Weight Loss Wi...,Daniella Joy,2023-06-28T10:14:55Z,Why Do People Gain Weight After Weight Loss Wi...
48,cq9vIlzzshU,Not Losing Weight On OMAD? Let Me Help! | OMAD...,Daniella Joy,2023-06-14T08:38:29Z,Chatting all things OMAD - from troubleshootin...
49,eDVld1FBFqE,Why You Are NOT Losing Weight With OMAD | Inte...,Dy Ann - Mindset Coach for Women Over 50,2023-03-16T17:45:08Z,Why You Are NOT Losing Weight With OMAD | Inte...

In [120]:
df2.dtypes #displays the variable types

video_id         object
title            object
channel_title    object
published_at     object
description      object
dtype: object

In [129]:
df2['published_at'] = pd.to_datetime(df2['published_at'], errors='raise', utc=True) #converts variable 'published_at' into a date/time variable
df2['published_at'] = df2['published_at'].dt.strftime('%Y-%m') #formats the variable into year - month

df2 #display dataframe to check work

,video_id,title,channel_title,published_at,description
0,FO7RPT6XLuQ,"OMAD, 2MAD, or just going mad? Fasting on a Ke...",Carnivore Talk,2026-04,"OMAD, 2MAD, or Just Plain MAD? Intermittent Fa..."
1,nw8SYbEARig,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-04,Kayla lost 80 pounds with intermittent fasting...
2,5yzDKwnTpnE,Intermittent Fasting and CKD: Is One Meal A Da...,Dadvice TV - Kidney Health Coach,2026-04,Are you confused about what to eat for Stage 3...
3,WmhVxALFxdY,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...
4,fsKfncwtJBE,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...
5,M0knw4F1wKc,"OMAD Keto Dinner Prep: Chicken, mince eggs A...",Miss Sarah M,2026-03,
6,A62b1L8gh-A,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...
7,ElteeBIkZvY,"Biblical Perspective Mindful Eating, Fasting, ...",BGK Mindful Eating,2026-02,"This isn't about eating less, eliminating, or ..."
8,Ndmm6U_93Bo,"New Year, New You! Intermittent Fasting, OMAD ...",Six Miles To Supper,2026-01,Kayla lost 80 pounds with intermittent fasting...
9,Ytxo_6-SWdo,OMAD Shaggy Locs Explains The Benefits &amp; I...,BSA Queen Goddess,2025-12,One Meal A Day Shaggy Locs Explains Why U Shou...
10,FWI38bG5JIw,Live Eating Of Todays OMAD Fastbreaking Meal,MIKE SAHA,2025-11,Live Eating Of Todays OMAD Fastbreaking Meal #...
11,qP-ZbAb-crU,"Live Cooking And Eating OMAD Meal, Speaking",MIKE SAHA,2025-10,"Live Cooking And Eating OMAD Meal, Speaking #F..."
12,EFbZpYAPtQg,OMAD diet plan chart (weight loss ),awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
13,SE_Ssjyc9JE,Eating My OMAD Fastbreaking Meal (One Meal A D...,MIKE SAHA,2025-10,Eating My OMAD Fastbreaking Meal (One Meal A D...
14,5cfUhAqcM_c,OMAD diet chart for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
15,Wqm67-silS0,OMAD diet plan,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
16,ZVc47uu3KD0,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
17,YQheeH5yeM4,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
18,tz2YmLpH06I,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
19,zUwGLKRByxc,Omad diet plan for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...
20,SrveDbiTQ_E,"JANGAN BUAT IF, OMAD #diet #fitness #fyp",Raeiz Hamed (RHTV),2025-10,trending #natural #viral Please Tekan Button S...
21,ziIJ4X3AnwQ,Day 1 Omad diet Weight loss diet starting weig...,Mieka The Habit Coach,2025-08,Join my skool community for fun monthly weight...
22,Irdvlv6O1PA,My OMAD Diet Rules | Case Study | Q&amp;A Live...,Fat to Fab,2025-07,For Personalized Diet Plans: Email - Enquiry@s...
23,RZjKtrT5UZs,MIKE SAHA LIVE OMAD MEALPREP / EATING,MIKE SAHA,2025-06,Mealprep video and eating ...
24,TP6epkBS6xY,LIVE MUKBANG OMAD MEAL EATING,MIKE SAHA,2025-06,LIVE MUKBANG OMAD MEAL EATING ...
25,0FNuOtrEmNk,Eating My Fastbreaking OMAD MEAL MIKE SAHA is ...,MIKE SAHA,2025-05,Eating my OMAD fastrbeaking meal ...
26,VkKZMb8uGVo,Mieka live Mukbang Omad diet #mukbang #eating ...,Mieka vs Nikki,2025-05,
27,Ii4b2ZerKhs,My Complete 30 Day OMAD Diet Weight Loss Chall...,Mieka The Habit Coach,2025-05,Join this channel to support their goals & Get...
28,S8dwV7TkwRc,| Day 6 | One meal a day diet #food #mukbang #...,MotionManTg,2025-03,
29,cjahrugNcwk,"Fasting &amp; Inflammation! Ready, Set, Go! OM...",My WeightLoss Journey By Keto Granny,2025-02,Join this channel to get access to perks: http...
30,mpkO8u4eU5Q,OMAD + A Cucumber For Weight Loss #weightloss ...,Mieka The Habit Coach,2024-11,Join this channel to support their goals & Get...
31,VKBgMvC_Ops,OMAD for 10 months✨️|OMAD diet results|OMAD be...,Jennifer Santos,2024-10,Don't underestimate the power of walking and f...
32,f2y7iTEyOik,The Ultimate Guide to the One Meal a Day Diet ...,Mike Cola,2024-08,The Ultimate Guide to the One Meal a Day Diet ...
33,NllKcY2nXRs,One Meal A Day (OMAD) Diet: How to Do it Corre...,Daniella Joy,2024-01,One Meal A Day (OMAD) Diet: How to Do it Corre...
34,igFVMTavE5Q,My Experience with OMAD + Carnivore Diet,Daniella Joy,2023-11,My Experience with OMAD + Carnivore Diet ... s...
35,Oc_hWisp4WM,Omad Diet Weight Loss Vlog Day 40 #weightloss ...,Mieka The Habit Coach,2023-10,I am on a weight loss journey to lose over 90 ...
36,uTei63rneH0,Live nutrition @DorianPicard : Omad / Carnivor...,ON THE WHEY,2023-10,Mon instagram : https://www.instagram.com/on_t...
37,u84wxd95ktY,Intermittent Fasting Schedule - Actual Hours a...,Intermittent Fasting Foodie,2023-09,I love intermittent fasting and have been eati...
38,0F_dcjNIz0o,Intermittent Fasting Schedule - Actual Hours a...,Intermittent Fasting Foodie,2023-09,I love intermittent fasting and have been eati...
39,SvH2tXzpKNg,Week of Fasting (&amp; Eating) My Exact Hours!...,Intermittent Fasting Foodie,2023-09,I love intermittent fasting and have been eati...
40,9lJXN9Yk3Bg,OMAD (ONE MEAL A DAY) SEPTEMBER WEIGHT LOSS CH...,Lih Lately,2023-09,loseweightfast #loseweighthealthy #omad #oneme...
41,V24FNaNOI0s,Do you know about OMAD Diet?,IHW tv,2023-08,OMAD Diet also known as warrior diet is all ab...
42,dQtEfqSudPE,Mastering OMAD: 10 Habits for Guaranteed Weigh...,Daniella Joy,2023-08,Mastering OMAD: 10 Habits for Guaranteed Weigh...
43,E2PCIUN39Aw,Episode #34 Omad weight loss.,AirborneOutdoorZ,2023-08,"Acceptance,commitment training."
44,04ouBqx0YGs,YOU CAN PRIORITIZE WEIGHT LOSS VIA OMAD MEALS ...,Daniella Joy,2023-07,YOU CAN PRIORITIZE WEIGHT LOSS VIA OMAD MEALS ...
45,P0koLtpXH7A,Live at 5:00 | OMAD One Meal A Day,Live Savage,2023-07,And other questions and answers!
46,ZIxqd_vCS1E,THE FASTER THE OMAD EATING WINDOW THE FASTER T...,Daniella Joy,2023-07,THE FASTER THE OMAD EATING WINDOW THE FASTER T...
47,bOHkMwWdnPs,Why Do People Gain Weight After Weight Loss Wi...,Daniella Joy,2023-06,Why Do People Gain Weight After Weight Loss Wi...
48,cq9vIlzzshU,Not Losing Weight On OMAD? Let Me Help! | OMAD...,Daniella Joy,2023-06,Chatting all things OMAD - from troubleshootin...
49,eDVld1FBFqE,Why You Are NOT Losing Weight With OMAD | Inte...,Dy Ann - Mindset Coach for Women Over 50,2023-03,Why You Are NOT Losing Weight With OMAD | Inte...

In [109]:
freddata = pd.read_csv('/Users/baileycarpenter/Downloads/CORESTICKM159SFRBATL (1).csv') #import data from fred
freddata['observation_date'] = pd.to_datetime(freddata['observation_date']).dt.strftime('%Y-%m')#convert observation_date to just year and month format

In [130]:
# Merge df2 and freddata dataframes using different column names for dates
# Use left_on and right_on when column names differ between dataframes
merged_df = pd.merge(
    df2, 
    freddata, 
    left_on='published_at',  # Column from df2
    right_on='observation_date',  # Column from freddata
    how='inner'
)

In [131]:
merged_df #view merged dataframe to check work

,video_id,title,channel_title,published_at,description,observation_date,CORESTICKM159SFRBATL
0,WmhVxALFxdY,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321
1,fsKfncwtJBE,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321
2,M0knw4F1wKc,"OMAD Keto Dinner Prep: Chicken, mince eggs A...",Miss Sarah M,2026-03,,2026-03,2.929321
3,A62b1L8gh-A,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321
4,ElteeBIkZvY,"Biblical Perspective Mindful Eating, Fasting, ...",BGK Mindful Eating,2026-02,"This isn't about eating less, eliminating, or ...",2026-02,2.903909
5,Ndmm6U_93Bo,"New Year, New You! Intermittent Fasting, OMAD ...",Six Miles To Supper,2026-01,Kayla lost 80 pounds with intermittent fasting...,2026-01,2.979751
6,Ytxo_6-SWdo,OMAD Shaggy Locs Explains The Benefits &amp; I...,BSA Queen Goddess,2025-12,One Meal A Day Shaggy Locs Explains Why U Shou...,2025-12,3.006319
7,FWI38bG5JIw,Live Eating Of Todays OMAD Fastbreaking Meal,MIKE SAHA,2025-11,Live Eating Of Todays OMAD Fastbreaking Meal #...,2025-11,2.954815
8,qP-ZbAb-crU,"Live Cooking And Eating OMAD Meal, Speaking",MIKE SAHA,2025-10,"Live Cooking And Eating OMAD Meal, Speaking #F...",2025-10,3.077827
9,EFbZpYAPtQg,OMAD diet plan chart (weight loss ),awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
10,SE_Ssjyc9JE,Eating My OMAD Fastbreaking Meal (One Meal A D...,MIKE SAHA,2025-10,Eating My OMAD Fastbreaking Meal (One Meal A D...,2025-10,3.077827
11,5cfUhAqcM_c,OMAD diet chart for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
12,Wqm67-silS0,OMAD diet plan,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
13,ZVc47uu3KD0,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
14,YQheeH5yeM4,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
15,tz2YmLpH06I,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
16,zUwGLKRByxc,Omad diet plan for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
17,SrveDbiTQ_E,"JANGAN BUAT IF, OMAD #diet #fitness #fyp",Raeiz Hamed (RHTV),2025-10,trending #natural #viral Please Tekan Button S...,2025-10,3.077827
18,ziIJ4X3AnwQ,Day 1 Omad diet Weight loss diet starting weig...,Mieka The Habit Coach,2025-08,Join my skool community for fun monthly weight...,2025-08,3.430945
19,Irdvlv6O1PA,My OMAD Diet Rules | Case Study | Q&amp;A Live...,Fat to Fab,2025-07,For Personalized Diet Plans: Email - Enquiry@s...,2025-07,3.427070
20,RZjKtrT5UZs,MIKE SAHA LIVE OMAD MEALPREP / EATING,MIKE SAHA,2025-06,Mealprep video and eating ...,2025-06,3.302508
21,TP6epkBS6xY,LIVE MUKBANG OMAD MEAL EATING,MIKE SAHA,2025-06,LIVE MUKBANG OMAD MEAL EATING ...,2025-06,3.302508
22,0FNuOtrEmNk,Eating My Fastbreaking OMAD MEAL MIKE SAHA is ...,MIKE SAHA,2025-05,Eating my OMAD fastrbeaking meal ...,2025-05,3.167990
23,VkKZMb8uGVo,Mieka live Mukbang Omad diet #mukbang #eating ...,Mieka vs Nikki,2025-05,,2025-05,3.167990
24,Ii4b2ZerKhs,My Complete 30 Day OMAD Diet Weight Loss Chall...,Mieka The Habit Coach,2025-05,Join this channel to support their goals & Get...,2025-05,3.167990
25,S8dwV7TkwRc,| Day 6 | One meal a day diet #food #mukbang #...,MotionManTg,2025-03,,2025-03,3.265924
26,cjahrugNcwk,"Fasting &amp; Inflammation! Ready, Set, Go! OM...",My WeightLoss Journey By Keto Granny,2025-02,Join this channel to get access to perks: http...,2025-02,3.520917
27,mpkO8u4eU5Q,OMAD + A Cucumber For Weight Loss #weightloss ...,Mieka The Habit Coach,2024-11,Join this channel to support their goals & Get...,2024-11,3.890823
28,VKBgMvC_Ops,OMAD for 10 months✨️|OMAD diet results|OMAD be...,Jennifer Santos,2024-10,Don't underestimate the power of walking and f...,2024-10,3.975247
29,f2y7iTEyOik,The Ultimate Guide to the One Meal a Day Diet ...,Mike Cola,2024-08,The Ultimate Guide to the One Meal a Day Diet ...,2024-08,4.111789

In [132]:
merged_df = merged_df.rename(columns={'CORESTICKM159SFRBATL' : 'CPI'}) #rename cpi column appropriately

In [133]:
merged_df #check work

,video_id,title,channel_title,published_at,description,observation_date,CPI
0,WmhVxALFxdY,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321
1,fsKfncwtJBE,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321
2,M0knw4F1wKc,"OMAD Keto Dinner Prep: Chicken, mince eggs A...",Miss Sarah M,2026-03,,2026-03,2.929321
3,A62b1L8gh-A,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321
4,ElteeBIkZvY,"Biblical Perspective Mindful Eating, Fasting, ...",BGK Mindful Eating,2026-02,"This isn't about eating less, eliminating, or ...",2026-02,2.903909
5,Ndmm6U_93Bo,"New Year, New You! Intermittent Fasting, OMAD ...",Six Miles To Supper,2026-01,Kayla lost 80 pounds with intermittent fasting...,2026-01,2.979751
6,Ytxo_6-SWdo,OMAD Shaggy Locs Explains The Benefits &amp; I...,BSA Queen Goddess,2025-12,One Meal A Day Shaggy Locs Explains Why U Shou...,2025-12,3.006319
7,FWI38bG5JIw,Live Eating Of Todays OMAD Fastbreaking Meal,MIKE SAHA,2025-11,Live Eating Of Todays OMAD Fastbreaking Meal #...,2025-11,2.954815
8,qP-ZbAb-crU,"Live Cooking And Eating OMAD Meal, Speaking",MIKE SAHA,2025-10,"Live Cooking And Eating OMAD Meal, Speaking #F...",2025-10,3.077827
9,EFbZpYAPtQg,OMAD diet plan chart (weight loss ),awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
10,SE_Ssjyc9JE,Eating My OMAD Fastbreaking Meal (One Meal A D...,MIKE SAHA,2025-10,Eating My OMAD Fastbreaking Meal (One Meal A D...,2025-10,3.077827
11,5cfUhAqcM_c,OMAD diet chart for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
12,Wqm67-silS0,OMAD diet plan,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
13,ZVc47uu3KD0,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
14,YQheeH5yeM4,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
15,tz2YmLpH06I,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
16,zUwGLKRByxc,Omad diet plan for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827
17,SrveDbiTQ_E,"JANGAN BUAT IF, OMAD #diet #fitness #fyp",Raeiz Hamed (RHTV),2025-10,trending #natural #viral Please Tekan Button S...,2025-10,3.077827
18,ziIJ4X3AnwQ,Day 1 Omad diet Weight loss diet starting weig...,Mieka The Habit Coach,2025-08,Join my skool community for fun monthly weight...,2025-08,3.430945
19,Irdvlv6O1PA,My OMAD Diet Rules | Case Study | Q&amp;A Live...,Fat to Fab,2025-07,For Personalized Diet Plans: Email - Enquiry@s...,2025-07,3.427070
20,RZjKtrT5UZs,MIKE SAHA LIVE OMAD MEALPREP / EATING,MIKE SAHA,2025-06,Mealprep video and eating ...,2025-06,3.302508
21,TP6epkBS6xY,LIVE MUKBANG OMAD MEAL EATING,MIKE SAHA,2025-06,LIVE MUKBANG OMAD MEAL EATING ...,2025-06,3.302508
22,0FNuOtrEmNk,Eating My Fastbreaking OMAD MEAL MIKE SAHA is ...,MIKE SAHA,2025-05,Eating my OMAD fastrbeaking meal ...,2025-05,3.167990
23,VkKZMb8uGVo,Mieka live Mukbang Omad diet #mukbang #eating ...,Mieka vs Nikki,2025-05,,2025-05,3.167990
24,Ii4b2ZerKhs,My Complete 30 Day OMAD Diet Weight Loss Chall...,Mieka The Habit Coach,2025-05,Join this channel to support their goals & Get...,2025-05,3.167990
25,S8dwV7TkwRc,| Day 6 | One meal a day diet #food #mukbang #...,MotionManTg,2025-03,,2025-03,3.265924
26,cjahrugNcwk,"Fasting &amp; Inflammation! Ready, Set, Go! OM...",My WeightLoss Journey By Keto Granny,2025-02,Join this channel to get access to perks: http...,2025-02,3.520917
27,mpkO8u4eU5Q,OMAD + A Cucumber For Weight Loss #weightloss ...,Mieka The Habit Coach,2024-11,Join this channel to support their goals & Get...,2024-11,3.890823
28,VKBgMvC_Ops,OMAD for 10 months✨️|OMAD diet results|OMAD be...,Jennifer Santos,2024-10,Don't underestimate the power of walking and f...,2024-10,3.975247
29,f2y7iTEyOik,The Ultimate Guide to the One Meal a Day Diet ...,Mike Cola,2024-08,The Ultimate Guide to the One Meal a Day Diet ...,2024-08,4.111789

In [137]:
merged_df['cpi_change'] = merged_df['CPI'] - merged_df['CPI'].shift(1) #creates a variable that calculates the inflation adjusted CPI change 

merged_df #checks work

,video_id,title,channel_title,published_at,description,observation_date,CPI,video_age_months,cpi_change
0,WmhVxALFxdY,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321,0,NaN
1,fsKfncwtJBE,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321,0,0.000000
2,M0knw4F1wKc,"OMAD Keto Dinner Prep: Chicken, mince eggs A...",Miss Sarah M,2026-03,,2026-03,2.929321,0,0.000000
3,A62b1L8gh-A,"Weight Loss with Intermittent Fasting, OMAD Li...",Six Miles To Supper,2026-03,Kayla lost 80 pounds with intermittent fasting...,2026-03,2.929321,0,0.000000
4,ElteeBIkZvY,"Biblical Perspective Mindful Eating, Fasting, ...",BGK Mindful Eating,2026-02,"This isn't about eating less, eliminating, or ...",2026-02,2.903909,0,-0.025412
5,Ndmm6U_93Bo,"New Year, New You! Intermittent Fasting, OMAD ...",Six Miles To Supper,2026-01,Kayla lost 80 pounds with intermittent fasting...,2026-01,2.979751,0,0.075842
6,Ytxo_6-SWdo,OMAD Shaggy Locs Explains The Benefits &amp; I...,BSA Queen Goddess,2025-12,One Meal A Day Shaggy Locs Explains Why U Shou...,2025-12,3.006319,0,0.026568
7,FWI38bG5JIw,Live Eating Of Todays OMAD Fastbreaking Meal,MIKE SAHA,2025-11,Live Eating Of Todays OMAD Fastbreaking Meal #...,2025-11,2.954815,0,-0.051504
8,qP-ZbAb-crU,"Live Cooking And Eating OMAD Meal, Speaking",MIKE SAHA,2025-10,"Live Cooking And Eating OMAD Meal, Speaking #F...",2025-10,3.077827,0,0.123012
9,EFbZpYAPtQg,OMAD diet plan chart (weight loss ),awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827,0,0.000000
10,SE_Ssjyc9JE,Eating My OMAD Fastbreaking Meal (One Meal A D...,MIKE SAHA,2025-10,Eating My OMAD Fastbreaking Meal (One Meal A D...,2025-10,3.077827,0,0.000000
11,5cfUhAqcM_c,OMAD diet chart for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827,0,0.000000
12,Wqm67-silS0,OMAD diet plan,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827,0,0.000000
13,ZVc47uu3KD0,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827,0,0.000000
14,YQheeH5yeM4,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827,0,0.000000
15,tz2YmLpH06I,OMAD diet plan chart for weight loss ( one mea...,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827,0,0.000000
16,zUwGLKRByxc,Omad diet plan for weight loss,awais latif,2025-10,https://youtube.com/@mawaislatif?si=52c7lXjWW5...,2025-10,3.077827,0,0.000000
17,SrveDbiTQ_E,"JANGAN BUAT IF, OMAD #diet #fitness #fyp",Raeiz Hamed (RHTV),2025-10,trending #natural #viral Please Tekan Button S...,2025-10,3.077827,0,0.000000
18,ziIJ4X3AnwQ,Day 1 Omad diet Weight loss diet starting weig...,Mieka The Habit Coach,2025-08,Join my skool community for fun monthly weight...,2025-08,3.430945,0,0.353118
19,Irdvlv6O1PA,My OMAD Diet Rules | Case Study | Q&amp;A Live...,Fat to Fab,2025-07,For Personalized Diet Plans: Email - Enquiry@s...,2025-07,3.427070,0,-0.003875
20,RZjKtrT5UZs,MIKE SAHA LIVE OMAD MEALPREP / EATING,MIKE SAHA,2025-06,Mealprep video and eating ...,2025-06,3.302508,0,-0.124562
21,TP6epkBS6xY,LIVE MUKBANG OMAD MEAL EATING,MIKE SAHA,2025-06,LIVE MUKBANG OMAD MEAL EATING ...,2025-06,3.302508,0,0.000000
22,0FNuOtrEmNk,Eating My Fastbreaking OMAD MEAL MIKE SAHA is ...,MIKE SAHA,2025-05,Eating my OMAD fastrbeaking meal ...,2025-05,3.167990,0,-0.134519
23,VkKZMb8uGVo,Mieka live Mukbang Omad diet #mukbang #eating ...,Mieka vs Nikki,2025-05,,2025-05,3.167990,0,0.000000
24,Ii4b2ZerKhs,My Complete 30 Day OMAD Diet Weight Loss Chall...,Mieka The Habit Coach,2025-05,Join this channel to support their goals & Get...,2025-05,3.167990,0,0.000000
25,S8dwV7TkwRc,| Day 6 | One meal a day diet #food #mukbang #...,MotionManTg,2025-03,,2025-03,3.265924,0,0.097935
26,cjahrugNcwk,"Fasting &amp; Inflammation! Ready, Set, Go! OM...",My WeightLoss Journey By Keto Granny,2025-02,Join this channel to get access to perks: http...,2025-02,3.520917,0,0.254993
27,mpkO8u4eU5Q,OMAD + A Cucumber For Weight Loss #weightloss ...,Mieka The Habit Coach,2024-11,Join this channel to support their goals & Get...,2024-11,3.890823,0,0.369905
28,VKBgMvC_Ops,OMAD for 10 months✨️|OMAD diet results|OMAD be...,Jennifer Santos,2024-10,Don't underestimate the power of walking and f...,2024-10,3.975247,0,0.084424
29,f2y7iTEyOik,The Ultimate Guide to the One Meal a Day Diet ...,Mike Cola,2024-08,The Ultimate Guide to the One Meal a Day Diet ...,2024-08,4.111789,0,0.136542

In [142]:
merged_df.to_csv('finalcsv', index = False) #exports file as finalcsv

I decided to change my dataframe parameters due to the lack of returns from the initial request. To